"""
run_total.py
------------
Experiment 1: predict hourly FLOOR TOTAL energy.
Loops floors x {with lags, without lags}, runs all 5 models, saves tables.

Floors used: 2, 3, 4, 5, 7
  (Floor 1 excluded: no indoor sensors. Floor 6 excluded: source file ends 22 Oct 2019.)

Split: one SHARED calendar test period for every floor (default 1 Nov - 31 Dec 2019).
Training = all usable hours before it; tuning uses training-only TimeSeriesSplit CV.
Models are ranked by training CV only: per floor by CV RMSE (cv_rank), across floors by
normalized CV(RMSE) % (CV RMSE / mean training load) and mean rank. The test period is only
used to report final performance.

Usage (from repo root):
  python src/run_total.py
  python src/run_total.py --floors 7          # quick single-floor run

Outputs:
  results/tables/total_all.csv             every floor x model x version, all metrics
  results/tables/total_summary.csv         paper-style table: median across floors
  results/tables/total_lag_vs_nolag.csv    test R2 with vs without lags
  results/tables/total_skipped.csv         floors skipped (too few train/test hours or missing)
  results/predictions/floorN_lags|nolags.csv   hourly actual vs predicted (for plots)
  With --sensor-lag 1 (Amendment 1) every file gets a "_sensorlag1" suffix, plus
  results/tables/total_vs_main_sensorlag1.csv: head-to-head vs the frozen main run, with
  metrics recomputed on evaluation timestamps shared by both runs (plus each run's own
  evaluation row count / date range and training rows).
"""

import argparse
import os
import time

import numpy as np
import pandas as pd

from features import date_split, get_frame, load_clean, make_features
from metrics import regression_metrics
from models import run_experiment

FLOORS = [2, 3, 4, 5, 7]
TEST_START = "2019-11-01"
MIN_TRAIN, MIN_TEST = 1600, 400   # usable hours needed before / after TEST_START
KEY = ["r2", "mse", "rmse", "vaf_pct", "a20_pct", "ioa", "cvrmse_pct", "nmbe_pct"]


def usable_split(clean_path, test_start, sensor_lag=0):
    """Usable (train, test) hours: valid floor_total AND full lag history.
    Same rows for both lag versions."""
    X, y = make_features(get_frame(load_clean(clean_path), "floor_total"), lags=True,
                         sensor_lag=sensor_lag)
    X_tr, X_te, _, _ = date_split(X, y, test_start)
    return len(X_tr), len(X_te)


def save_predictions(path, clean_path, use_lags, fitted, test_start, sensor_lag=0, keep_index=None):
    """Hourly actual vs each model's prediction on the shared test period."""
    X, y = make_features(get_frame(load_clean(clean_path), "floor_total"), lags=use_lags,
                         sensor_lag=sensor_lag)
    if keep_index is not None:
        keep = X.index.isin(keep_index)
        X, y = X[keep], y[keep]
    _, X_te, _, y_te = date_split(X, y, test_start)
    out = pd.DataFrame({"actual": y_te})
    for name, search in fitted.items():
        out[name] = np.clip(search.best_estimator_.predict(X_te), 0.0, None)
    out.to_csv(path)


def shared_index(clean_path, lags):
    """Timestamps valid under BOTH sensor_lag=0 and sensor_lag=1 (Amendment 1)."""
    frame = get_frame(load_clean(clean_path), "floor_total")
    X0, _ = make_features(frame, lags=lags, sensor_lag=0)
    X1, _ = make_features(frame, lags=lags, sensor_lag=1)
    return X0.index.intersection(X1.index)


def train_index(clean_path, lags, sensor_lag, test_start, keep_index):
    X, y = make_features(get_frame(load_clean(clean_path), "floor_total"), lags=lags,
                         sensor_lag=sensor_lag)
    X = X[X.index.isin(keep_index)]
    return X.index[X.index < pd.Timestamp(test_start)]


def rows_match_main(clean_path, test_start):
    """Amendment 1 fairness check: training AND evaluation timestamps must be identical
    between sensor_lag=0 and sensor_lag=1 as generated by the CURRENT code, for both feature
    sets. (Consistency with the frozen run is checked separately by matches_frozen_run.)
    Returns a list of problems (empty = identical)."""
    frame = get_frame(load_clean(clean_path), "floor_total")
    problems = []
    for lags in (True, False):
        X0, y0 = make_features(frame, lags=lags, sensor_lag=0)
        X1, y1 = make_features(frame, lags=lags, sensor_lag=1)
        tr0, te0, _, _ = date_split(X0, y0, test_start)
        tr1, te1, _, _ = date_split(X1, y1, test_start)
        for part, a, b in (("train", tr0.index, tr1.index), ("eval", te0.index, te1.index)):
            if not a.equals(b):
                problems.append(f"lags={lags} {part}: {len(a.difference(b))} hours only in main, "
                                f"{len(b.difference(a))} only in sensor-lag")
    return problems


def matches_frozen_run(clean_path, floor, test_start, tables_dir, preds_dir):
    """Check regenerated lag-0 rows against the FROZEN main run's saved artifacts:
    evaluation timestamps exactly (prediction files); training rows by count and first/last
    timestamp (total_all.csv - the full training index was not saved).
    Returns a list of problems (empty = consistent)."""
    main_path = os.path.join(tables_dir, "total_all.csv")
    if not os.path.exists(main_path):
        return ["frozen total_all.csv not found"]
    main_all = pd.read_csv(main_path)
    frame = get_frame(load_clean(clean_path), "floor_total")
    problems = []
    for lags in (True, False):
        tag = "lags" if lags else "nolags"
        X, y = make_features(frame, lags=lags, sensor_lag=0)
        tr, te, _, _ = date_split(X, y, test_start)
        meta = main_all.query("floor == @floor and lags == @lags")
        if meta.empty:
            problems.append(f"lags={lags}: floor not in frozen total_all.csv"); continue
        m = meta.iloc[0]
        if (len(tr), str(tr.index.min()), str(tr.index.max())) != (
                int(m.n_train), str(pd.Timestamp(m.train_start)), str(pd.Timestamp(m.train_end))):
            problems.append(f"lags={lags} train: regenerated {len(tr)} rows {tr.index.min()}..{tr.index.max()} "
                            f"vs frozen {m.n_train} rows {m.train_start}..{m.train_end}")
        pred_path = os.path.join(preds_dir, f"floor{floor}_{tag}.csv")
        if not os.path.exists(pred_path):
            problems.append(f"lags={lags}: frozen prediction file not found"); continue
        frozen_eval = pd.read_csv(pred_path, parse_dates=["Date"], index_col="Date").index
        if not te.index.equals(frozen_eval):
            problems.append(f"lags={lags} eval: {len(te.index.difference(frozen_eval))} regenerated hours not in "
                            f"frozen run, {len(frozen_eval.difference(te.index))} frozen hours not regenerated")
    return problems


def compare_on_shared_hours(preds_dir, tables_dir, sfx, allres, baselines=None):
    """Recompute both runs' metrics on the evaluation timestamps present in BOTH runs.
    Also reports each run's own evaluation row count / date range and training rows."""
    main_path = os.path.join(tables_dir, "total_all.csv")
    if not os.path.exists(main_path):
        print("Main run total_all.csv not found - skipping head-to-head comparison.")
        return None
    main_all = pd.read_csv(main_path)
    rows = []
    for (floor, lags), _ in allres.groupby(["floor", "lags"]):
        tag = "lags" if lags else "nolags"
        base = (baselines or {}).get((floor, lags))
        p_main = base[0] if base else os.path.join(preds_dir, f"floor{floor}_{tag}.csv")
        p_new = os.path.join(preds_dir, f"floor{floor}_{tag}{sfx}.csv")
        if not (os.path.exists(p_main) and os.path.exists(p_new)):
            print(f"Floor {floor} {tag}: prediction file missing - not compared")
            continue
        a = pd.read_csv(p_main, parse_dates=["Date"], index_col="Date")
        b = pd.read_csv(p_new, parse_dates=["Date"], index_col="Date")
        shared = a.index.intersection(b.index)
        n_tr_main = (base[1] if base else
                     main_all.query("floor == @floor and lags == @lags")["n_train"].iloc[0])
        n_tr_new = allres.query("floor == @floor and lags == @lags")["n_train"].iloc[0]
        for model in a.columns.drop("actual"):
            sa = regression_metrics(a.loc[shared, "actual"], a.loc[shared, model])
            sb = regression_metrics(b.loc[shared, "actual"], b.loc[shared, model])
            rows.append({
                "floor": floor, "lags": lags, "model": model,
                "baseline": "matched refit on shared hours" if base else "frozen main run",
                "n_eval_main": len(a), "eval_main_start": a.index.min(), "eval_main_end": a.index.max(),
                "n_eval_sensorlag": len(b), "eval_sensorlag_start": b.index.min(),
                "eval_sensorlag_end": b.index.max(), "n_shared": len(shared),
                "n_train_main": n_tr_main, "n_train_sensorlag": n_tr_new,
                "r2_main_shared": sa["r2"], "r2_sensorlag_shared": sb["r2"],
                "r2_change_shared": sb["r2"] - sa["r2"],
                "cvrmse_main_shared": sa["cvrmse_pct"], "cvrmse_sensorlag_shared": sb["cvrmse_pct"],
                "nmbe_main_shared": sa["nmbe_pct"], "nmbe_sensorlag_shared": sb["nmbe_pct"],
            })
    return pd.DataFrame(rows) if rows else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clean-dir", default="data/clean")
    ap.add_argument("--floors", nargs="+", type=int, default=FLOORS)
    ap.add_argument("--test-start", default=TEST_START)
    ap.add_argument("--tables", default="results/tables")
    ap.add_argument("--preds", default="results/predictions")
    ap.add_argument("--sensor-lag", type=int, default=0, choices=[0, 1],
                    help="Amendment 1: 1 = use previous-hour sensor readings (post-hoc run)")
    args = ap.parse_args()
    sfx = f"_sensorlag{args.sensor_lag}" if args.sensor_lag else ""   # never overwrite main run
    T = lambda name: os.path.join(args.tables, f"{name}{sfx}.csv")
    os.makedirs(args.tables, exist_ok=True)
    os.makedirs(args.preds, exist_ok=True)

    # Amendment 1 checks:
    #  - lag-0 rows must match the frozen run's artifacts, otherwise stop;
    #  - if lag-0 and lag-1 rows differ on a floor, that floor is PAIRED: both the sensor-lag
    #    run and a matched lag-0 baseline (frozen config, no retuning) train on shared hours.
    paired = set()
    if args.sensor_lag:
        bad = {}
        for floor in args.floors:
            path = os.path.join(args.clean_dir, f"floor{floor}_hourly.csv")
            if not os.path.exists(path):
                continue
            frozen = matches_frozen_run(path, floor, args.test_start, args.tables, args.preds)
            if frozen:
                bad[floor] = frozen
                continue
            lagdiff = rows_match_main(path, args.test_start)
            if lagdiff:
                paired.add(floor)
                for msg in lagdiff:
                    print(f"Floor {floor}: lag-0 vs lag-1 rows differ ({msg}) -> PAIRED on shared hours")
            else:
                print(f"Floor {floor}: lag-0 rows consistent with frozen run "
                      f"(eval exact; train count+range) and lag-1 rows identical to lag-0 [OK]")
        if bad:
            for floor, problems in bad.items():
                for msg in problems:
                    print(f"Floor {floor}: MISMATCH WITH FROZEN RUN - {msg}")
            raise SystemExit("Stopped before training: regenerated rows differ from the frozen main run.")
    baselines, base_rows = {}, []

    rows, skipped = [], []
    for floor in args.floors:
        clean_path = os.path.join(args.clean_dir, f"floor{floor}_hourly.csv")
        if not os.path.exists(clean_path):
            reason = "clean file not found"
        else:
            n_tr, n_te = usable_split(clean_path, args.test_start, args.sensor_lag)
            reason = (f"too few usable hours (train {n_tr} < {MIN_TRAIN} or test {n_te} < {MIN_TEST})"
                      if n_tr < MIN_TRAIN or n_te < MIN_TEST else None)
            if reason is None:
                print(f"Floor {floor}: usable train {n_tr} h, test {n_te} h [OK]")
        if reason:
            print(f"Floor {floor}: SKIPPED - {reason}")
            skipped.append({"floor": floor, "reason": reason})
            continue

        for use_lags in (True, False):
            tag = "lags" if use_lags else "nolags"
            t = time.time()
            keep = shared_index(clean_path, use_lags) if floor in paired else None
            if keep is not None:   # paired floor: identical training timestamps, asserted exactly
                assert train_index(clean_path, use_lags, 0, args.test_start, keep).equals(
                    train_index(clean_path, use_lags, 1, args.test_start, keep)), "paired train rows differ"
            res, fitted = run_experiment(clean_path, "floor_total", use_lags,
                                         test_start=args.test_start, sensor_lag=args.sensor_lag,
                                         keep_index=keep)
            res.insert(0, "floor", floor)
            rows.append(res)
            save_predictions(os.path.join(args.preds, f"floor{floor}_{tag}{sfx}.csv"),
                             clean_path, use_lags, fitted, args.test_start, args.sensor_lag, keep)
            if keep is not None:   # matched baseline: frozen lag-0 config on the same shared hours
                b_res, b_fit = run_experiment(clean_path, "floor_total", use_lags,
                                              test_start=args.test_start, sensor_lag=0, keep_index=keep)
                b_res.insert(0, "floor", floor)
                base_rows.append(b_res)
                b_path = os.path.join(args.preds, f"floor{floor}_{tag}_baseline_shared.csv")
                save_predictions(b_path, clean_path, use_lags, b_fit, args.test_start, 0, keep)
                baselines[(floor, use_lags)] = (b_path, int(b_res.n_train.iloc[0]))
                print(f"  {tag:6s} | matched lag-0 baseline refit on {int(b_res.n_train.iloc[0])} shared train hours")
            best = res.loc[res["cv_rmse_mean"].idxmin()]   # selection: training CV only
            print(f"  {tag:6s} | best by CV RMSE: {best.model} (CV {best.cv_rmse_mean:.2f}) "
                  f"-> test R2 {best.test_r2:.3f} | {time.time() - t:.0f}s")
        # checkpoint: a crash halfway keeps finished floors
        pd.concat(rows).to_csv(T("total_all"), index=False)

    if skipped:
        pd.DataFrame(skipped).to_csv(T("total_skipped"), index=False)
    if not rows:
        raise SystemExit("No floor had enough usable hours - nothing to report.")

    allres = pd.concat(rows, ignore_index=True)
    # per-floor rank by training CV RMSE (1 = best) - scale-free across floors
    allres["cv_rank"] = allres.groupby(["floor", "lags"])["cv_rmse_mean"].rank(method="min")
    # ASHRAE Guideline 14 hourly CALIBRATION thresholds, used here only as a reference point
    # for forecast accuracy - meeting them is not an ASHRAE "pass" for a forecasting model.
    allres["within_ashrae_calib_thresholds"] = (
        (allres.test_cvrmse_pct <= 30) & (allres.test_nmbe_pct.abs() <= 10))
    allres.to_csv(T("total_all"), index=False)

    # paper-style table: per model x version, training vs testing (median over floors)
    agg = {f"{s}_{k}": "median" for s in ("train", "test") for k in KEY}
    agg["cv_cvrmse_pct"] = "median"
    agg["cv_rank"] = "mean"
    agg["within_ashrae_calib_thresholds"] = "mean"
    summary = allres.groupby(["lags", "model"]).agg(agg).round(3)
    summary["within_ashrae_calib_thresholds"] = (summary["within_ashrae_calib_thresholds"] * 100).round(0)
    summary = (summary.rename(columns={"within_ashrae_calib_thresholds": "pct_floors_within_ashrae_calib"})
               .rename(columns={"cv_cvrmse_pct": "median_cv_cvrmse_pct", "cv_rank": "mean_cv_rank"})
               .sort_values(["lags", "median_cv_cvrmse_pct"]))
    summary.to_csv(T("total_summary"))

    lag_cmp = allres.pivot_table(index=["floor", "model"], columns="lags", values="test_r2").round(3)
    lag_cmp = lag_cmp.rename(columns={False: "r2_nolags", True: "r2_lags"})
    lag_cmp.to_csv(T("total_lag_vs_nolag"))

    # Amendment 1: head-to-head vs the frozen main run, on timestamps shared by both runs
    if sfx:
        if base_rows:
            pd.concat(base_rows, ignore_index=True).to_csv(T("total_baseline_shared"), index=False)
        cmp = compare_on_shared_hours(args.preds, args.tables, sfx, allres, baselines)
        if cmp is not None:
            num = cmp.select_dtypes("number").columns
            cmp[num] = cmp[num].round(4)
            cmp.to_csv(T("total_vs_main"), index=False)
            med = (cmp.groupby(["lags", "model"])[["r2_main_shared", "r2_sensorlag_shared", "r2_change_shared"]]
                   .median().round(3))
            print("\n=== Amendment 1 vs main run: median over floors, on SHARED evaluation hours ===")
            print(med.to_string())
            print("\nEvaluation coverage per floor/version (main vs sensor-lag):")
            print(cmp.drop_duplicates(["floor", "lags"])[
                ["floor", "lags", "baseline", "n_eval_main", "n_eval_sensorlag", "n_shared",
                 "n_train_main", "n_train_sensorlag"]].to_string(index=False))

    pd.set_option("display.width", 200)
    print(f"\n=== Across floors (ranked by median training CV(RMSE) %; test = {args.test_start} onward) ===")
    print(summary[["median_cv_cvrmse_pct", "mean_cv_rank"] + [f"test_{k}" for k in ("r2", "rmse", "cvrmse_pct", "nmbe_pct", "ioa")]
                  + ["pct_floors_within_ashrae_calib"]].to_string())
    print("\nReference: ASHRAE Guideline 14 hourly calibration thresholds, CV(RMSE) <= 30% and |NMBE| <= 10%.")
    print("These are calibration criteria, shown for comparison only - not an ASHRAE pass for forecasts.")
    print(f"\nSaved -> {args.tables}/ and {args.preds}/")


if __name__ == "__main__":
    main()
